id: PD775A70B
initial_creation_type: input
source_metadata:
  title: Dodrupchen Jigme Trinle Özer Series
  language: de
  description: 'Texts by the First Dodrupchen, Jigme Trinle Özer (rdo grub ’jigs med
    phrin las ''od zer, 1745–1821), who was also known as Kunzang Shenpen (kun bzang
    gzhan phan):'
  volume:
    1d5cc7810aad487682a02bd9e56c2fb4:
      title: Aspiration at the Moment of Death
      parent: Aspiration Prayers
    11aaaafc60e342e2a430c38d9fcf30ac:
      title: Brief Dharmapālas Offering
      parent: Dharma Protectors
    7b666b8a69f245b2801ddc236d3a18fe:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Guru Rinpoche prayers
    4d1ffbd262d949579f69a2397f55af43:
      title: 'A Constant Stream of Blessings: A Prayer to the Eight Supreme Vidyādharas
        of India'
      parent: Lineage Prayers
    9f9997053db847df8c7323854270e9ba:
      title: The Brief Ḍākinī Prayer
      parent: Lineage Prayers
    191e1a5a2b9641629824dd9e5bae8f8f:
      title: The Source of Accomplishment, the Fruit of the Two-Fold Truth—A Prayer
        to the Wisdom Ḍākinī Dechen Gyalmo
      parent: Lineage Prayers
    1fd9e5112ecf4c479c41dac45966a794:
      title: 'The Excellent Path to Omniscience: The Dzogchen Preliminary Practice
        of Longchen Nyingtik'
      parent: Ngöndro
    671579c12c35452eb4c948ed82cd80a0:
      title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren)
        for the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the
        Great Compassionate One from the Longchen Nyingtik'
      parent: Practices
    4d0597b133534e2c95d25d370ab0c83f:
      title: 'The Source of Abundant Merit: A Feast-Offering for the Secret Practice
        of the Great Compassionate One, Natural Liberation of Suffering from The Heart
        Essence of the Vast Expanse'
      parent: Practices
    443854b6140a4530b30bd20fb21ea455:
      title: 'The Stairway to Great Bliss: A Method for Planting the Seed of Liberation
        in Animals'
      parent: Practices
    3ebeeeff5bd943728dc6392048d81412:
      title: Detailed Visualization of the Great Compassionate One’s Retinue
      parent: Sādhanas
    3448b608f1f54beaaf96c6a99e680faf:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Sādhanas
created_at: '2022-02-28T23:00:39.690241'
last_modified_at: '2022-02-28T23:00:39.690244'
